name       : pyalsaaudio
version    : 0.9.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/23/b1/672d496718562301ce2052b07196ca31874e4f1a497881ae44b2279a4e1d/pyalsaaudio-0.9.0.tar.gz : 3ca069c736c8ad2a3047b5033468d983a2480f94fad4feb0169c056060e01e69
license    : Python-2.4
component  : programming.python
summary    : ALSA bindings
description: |
    Wrappers for accessing the ALSA API from Python. It is fairly complete for PCM devices and Mixer access.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
